import express from "express";
import helmet from "helmet";
import cors from "cors";
import compression from "compression";
import cookieParser from "cookie-parser";
import mongoSanitize from "express-mongo-sanitize";
import pinoHttp from "pino-http";
import { env } from "./config/env.js";
import { logger } from "./config/logger.js";
import { globalLimiter } from "./middleware/rateLimiter.js";
import { notFound, errorHandler } from "./middleware/errorHandler.js";
import routes from "./routes/index.js";

const app = express();
app.use(helmet());
app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(cookieParser());
app.use(compression());
app.use(mongoSanitize());
app.use(pinoHttp({ logger, autoLogging: { ignore: (req) => req.url === "/health" } }));
app.use(globalLimiter);
app.get("/health", (req, res) => {
  res.status(200).json({ success: true, message: "Service healthy", timestamp: new Date().toISOString() });
});
app.get("/", (req, res) => res.send("FlowDesk API running. Use /api/v1"));
app.use("/api/v1", routes);
app.use(notFound);
app.use(errorHandler);
export default app;
